services:
  wizley:
    image: git.codelab.tec.br/vctrtvfrrr/wizley:${IMAGE_TAG:-latest}
    container_name: wizley
    restart: unless-stopped
    networks:
      - web
    mem_limit: 32m
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wizley.rule=Host(`wizley.com.br`) || Host(`www.wizley.com.br`)"
      - "traefik.http.routers.wizley.entrypoints=websecure"
      - "traefik.http.routers.wizley.tls.certresolver=letsencrypt"
      - "traefik.http.routers.wizley.tls.domains[0].main=wizley.com.br"
      - "traefik.http.routers.wizley.tls.domains[0].sans=www.wizley.com.br"
      - "traefik.http.routers.wizley.middlewares=wizley-www-to-apex"
      - "traefik.http.services.wizley.loadbalancer.server.port=80"
      - "traefik.http.middlewares.wizley-www-to-apex.redirectregex.regex=^https?://www\\.wizley\\.com\\.br/(.*)"
      - "traefik.http.middlewares.wizley-www-to-apex.redirectregex.replacement=https://wizley.com.br/$${1}"

networks:
  web:
    external: true
